import Head from 'next/head'
import Image from 'next/image'

import Header from '@components/Header';
import Container from '@components/Container';

import styles from '@styles/Home.module.scss'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Header />

      <main>

        <Container >
          <h1>Hyper Bros. Trading Cards</h1>
            <h2>Available Cards</h2>
            <ul className={styles.products}>
                <li >
                    <img src = '/images/bowser-holo.jpg' alt = 'Bowser Holo' />
                    <h3>Bowser Holographic</h3>
                    <p>$99.99</p>
                    <p><button>Add to Cart</button></p>
                </li >

                 <li >
                    <img src = '/images/bowser-holo.jpg' alt = 'Bowser Holo' />
                    <h3>Bowser Holographic</h3>
                    <p>$99.99</p>
                    <p><button>Add to Cart</button></p>
                </li >

                 <li >
                    <img src = '/images/bowser-holo.jpg' alt = 'Bowser Holo' />
                    <h3>Bowser Holographic</h3>
                    <p>$99.99</p>
                    <p><button>Add to Cart</button></p>
                </li >

                </ul >
        </Container>

      </main>

      <footer className={styles.footer}>
&copy; Hyper Bros. Trading Cards, {new Date().getFullYear()}
      </footer>
    </div>
  )
}
